name: wagtail-images-deduplicator CI

on:
  push:
    branches:
      - main
      - "stable/**"

  pull_request:

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        django: ["3.2", "4.0"]
        wagtail: ["3.0", "4.0"]

        include:
          - wagtail: "4.0"
            django: "4.1"
            python: "3.10"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}

  lint:
    name: Lint ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]
        toxenv: ["black", "isort", "flake8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Run ${{ matrix.toxenv }}
        run: |
          tox
        env:
          TOXENV: ${{ matrix.toxenv }}
